[package]
name = "natureza"
version = "0.1.0"
authors = ["Vitor Silva <vitor@silva.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enet = "*"